name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  validate-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Validate PlatformIO examples build successfully
      run: |
        set -e
        examples=(SimpleGet PostWithData MultipleRequests CustomHeaders StreamingUpload CompileTest)
        for name in "${examples[@]}"; do
          echo "Building PlatformIO example: $name"
          dir="examples/platformio/${name}"
          test -f "$dir/platformio.ini" || (echo "Missing platformio.ini in $dir" && exit 1)
          test -f "$dir/src/main.cpp" || (echo "Missing src/main.cpp in $dir" && exit 1)
          (cd "$dir" && pio run -e esp32dev)
        done

    - name: Verify Arduino sketches exist
      run: |
        set -e
        examples=(SimpleGet PostWithData MultipleRequests CustomHeaders StreamingUpload CompileTest)
        for name in "${examples[@]}"; do
          sketch="examples/arduino/${name}/${name}.ino"
          test -f "$sketch" || (echo "Missing Arduino sketch: $sketch" && exit 1)
        done
    - name: Verify release metadata & consistency
      run: |
        bash scripts/verify-release.sh

    - name: Create source archive
      run: |
        VERSION=$(grep '"version"' library.json | sed -E 's/.*"version" *: *"([^"]+)".*/\1/')
        ARCHIVE="ESPAsyncWebClient-${VERSION}.zip"
        zip -r "$ARCHIVE" src examples README.md LICENSE library.json library.properties
        echo "Created $ARCHIVE"
        echo "ARCHIVE=$ARCHIVE" >> $GITHUB_ENV
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: source-archive
        path: ${{ env.ARCHIVE }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ARCHIVE }}
        name: Release ${{ github.ref }}
        body: |
          ## Changes in this release
          See the Git diff for this tag or the Releases page for details.
          
          ## Verification
          - Examples built successfully
          - Version metadata consistent
          - Source archive attached
