name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  validate-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Validate all examples build successfully
      run: |
        for example in examples/*; do
          if [ -d "$example" ]; then
            example_name=$(basename "$example")
            echo "Building example: $example_name"
            
            mkdir -p /tmp/release_test_$example_name/lib/ESPAsyncWebClient
            cp -r "$example"/* /tmp/release_test_$example_name/
            cp -r src/* /tmp/release_test_$example_name/lib/ESPAsyncWebClient/
            
            cat > /tmp/release_test_$example_name/platformio.ini << 'EOF'
        [platformio]
        default_envs = esp32dev
        
        [env]
        framework = arduino
        lib_deps = 
            https://github.com/ESP32Async/AsyncTCP.git
            bblanchon/ArduinoJson@^6.21.0
        
        [env:esp32dev]
        platform = espressif32
        board = esp32dev
        EOF
            
            cd /tmp/release_test_$example_name
            pio run
            cd -
          fi
        done
    - name: Verify release metadata & consistency
      run: |
        bash scripts/verify-release.sh

    - name: Create source archive
      run: |
        VERSION=$(grep '"version"' library.json | sed -E 's/.*"version" *: *"([^"]+)".*/\1/')
        ARCHIVE="ESPAsyncWebClient-${VERSION}.zip"
        zip -r "$ARCHIVE" src examples README.md LICENSE library.json library.properties
        echo "Created $ARCHIVE"
        echo "ARCHIVE=$ARCHIVE" >> $GITHUB_ENV
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: source-archive
        path: ${{ env.ARCHIVE }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ARCHIVE }}
        name: Release ${{ github.ref }}
        body: |
          ## Changes in this release
          See the Git diff for this tag or the Releases page for details.
          
          ## Verification
          - Examples built successfully
          - Version metadata consistent
          - Source archive attached
