name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  validate-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Validate all examples build successfully
      run: |
        for example in examples/*; do
          if [ -d "$example" ]; then
            example_name=$(basename "$example")
            echo "Building example: $example_name"
            
            mkdir -p /tmp/release_test_$example_name
            cp -r "$example"/* /tmp/release_test_$example_name/
            cp -r src /tmp/release_test_$example_name/lib/ESPAsyncWebClient/
            
            cat > /tmp/release_test_$example_name/platformio.ini << 'EOF'
        [platformio]
        default_envs = esp32dev, nodemcuv2
        
        [env]
        framework = arduino
        lib_deps = 
            https://github.com/me-no-dev/AsyncTCP.git
            bblanchon/ArduinoJson@^6.21.0
        
        [env:esp32dev]
        platform = espressif32
        board = esp32dev
        EOF
            
            cd /tmp/release_test_$example_name
            pio run
            cd -
          fi
        done
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## Changes in this release
          - All examples successfully build for ESP32
          - Library structure validated
          - Dependencies verified
          
          ## Platforms tested
          - ESP32 (espressif32)
          
          ## Dependencies
          - AsyncTCP
          - ArduinoJson (^6.21.0)
